RUN_STRINGS = (
    "Menurutmu kemana kamu akan pergi?",
    "Hah? Apa? Apakah mereka lolos?",
    "ZZzzZZzz ... Hah? Apa? Oh, hanya mereka lagi, lupakan.",
    "Kembali kesini!",
    "Tidak terlalu cepat ...",
    "Awas ke dinding!",
    "Jangan tinggalkan aku sendiri dengan mereka !!",
    "Kamu lari, kamu mati.",
    "Bercanda, aku ada dimana-mana",
    "Kamu akan menyesali itu ...",
    "Kamu juga bisa mencoba / punchme, kudengar itu menyenangkan.",
    "Ganggu orang lain, tidak ada yang peduli.",
    "Kamu bisa lari, tapi kamu tidak bisa bersembunyi.",
    "Apakah hanya itu yang kamu punya?",
    "Saya di belakang Anda...",
    "Anda punya teman!",
    "Kita bisa melakukan ini dengan cara mudah, atau cara sulit.",
    "Anda tidak mengerti, bukan?",
    "Ya, sebaiknya kau lari!",
    "Tolong, ingatkan saya betapa saya peduli?",
    "Aku akan berlari lebih cepat jika jadi kamu.",
    "Itu pasti droid yang kami cari.",
    "Semoga peluang selalu menguntungkan Anda.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    "\" Oh, lihat aku! Saya sangat keren, saya bisa lari dari bot! \ "- orang ini",
    "Ya ya, cukup ketuk / pukul aku.",
    "Ini, ambil cincin ini dan pergilah ke Mordor saat kamu melakukannya.",
    "Legenda mengatakan, mereka masih berjalan ...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan menyebabkan kemarahan. Kemarahan mengarah pada kebencian. Kebencian menyebabkan penderitaan. Jika Anda terus berlari dalam ketakutan, Anda mungkin"
    "jadilah Vader berikutnya.",
    "Beberapa kalkulasi nanti, saya telah memutuskan minat saya pada kejahatan Anda tepat 0.",
    "Legenda mengatakan, mereka masih berjalan.",
    "Teruskan, kami tidak yakin kami menginginkanmu di sini.",
    "Kamu seorang penyihir- Oh. Tunggu. Kamu bukan Harry, teruslah bergerak.",
    "TIDAK BERLARI DI HALLWAYS!",
    "Hasta la vista, sayang.",
    "Siapa yang membiarkan anjing keluar?",
    "Ini lucu, karena tidak ada yang peduli.",
    "Ah, sayang sekali. Aku suka yang itu.",
    "Terus terang, sayangku, aku tidak peduli.",
    "Milkshake saya membawa semua anak laki-laki ke halaman ... Jadi lari lebih cepat!",
    "Anda tidak bisa MENANGANI kebenaran!",
    "Dahulu kala, di galaksi yang sangat jauh ... Seseorang akan peduli tentang itu. Tapi sekarang tidak lagi.",
    "Hei, lihat mereka! Mereka lari dari palu yang tak terelakkan ... Manis.",
    "Han menembak lebih dulu. Aku juga.",
    "Apa yang kamu kejar, kelinci putih?",
    "Seperti yang dikatakan si manis ... LARI!",
)

SLAP_stella_TEMPLATES = (
    "Jika kau menamparku sekali lagi, Yunus Zend akan membunuhmu.",
    "Anak asu.",
    [
        "Saya membungkam Anda sebentar.", #normal reply
        "Berhenti menamparku, kau tahu siapa pemilikku 😏", #reply to admin
        "tmute" #command
    ]
)

SLAP_TEMPLATES = (
    "{user2} ditembak mati oleh {user1}.",
    "{user2} berjalan ke kaktus saat mencoba melarikan diri {user1}.",
    "{user2} tenggelam saat mencoba kabur {user1}.",
    "{user2} jatuh ke dalam sepetak kaktus.",
    "{user2} terbakar.",
    "{user2} terbakar sampai mati.",
    "{user2} terbakar habis saat melawan {user1}.",
    "{user2} tersambar petir.",
    "{user2} dibunuh oleh {user1}.",
    "{user2} dibunuh oleh sihir.",
    "{user2} mati kelaparan.",
    "{user2} jatuh dari dunia.",
    "{user2} dihempaskan ke dalam kehampaan oleh {user1}.",
    "Tulang {user2} terkikis bersih oleh angin sepi.",
    "{user2} pingsan.",
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} whited out !.",
    "{user2} kehabisan Pokemon yang dapat digunakan! {user2} pingsan !.",
    "{user2} mengucapkan selamat tinggal pada dunia yang kejam ini.",
    "{user2} mendapat rekt.",
    "{user2} digergaji menjadi dua oleh {user1}.",
    "melon {user2} telah dipisahkan oleh {user1}.",
    "{user2} telah diiris dan dipotong dadu oleh {user1}.",
    "Kematian {user2} membuat kedudukan lain di kapak {user1}.",
    "{user2} meninggal karena penyakit tropis misterius milik {user1}.",
    "{user2} memainkan kentang panas dengan granat.",
    "{user2} telah ditusuk oleh {user1}.",
    "{user2} makan granat.",
    "{user2} adalah untuk makan malam!",
    "{user2} dihentikan oleh {user1}.",
    "{user2} ditembak sebelum dilempar keluar dari pesawat.",
    "{user2} mengalami error.",
    "{user2} meninggal dan bereinkarnasi sebagai kambing.",
    "{user1} melempar {user2} dari gedung.",
    "{user2} mendapat penguburan prematur.",
    "{user1} mengirim spam email {user2}.",
    "{user1} tekan {user2} dengan pesawat ruang angkasa kecil antarbintang.",
    "{user1} masukkan {user2} di check-mate.",
    "{user1} RSA-encrypted {user2} dan menghapus kunci pribadi.",
    "{user1} letakkan {user2} di friendzone.",
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!",
    "{user2} meninggal karena gangren rumah sakit.",
    "{user2} mendapat telepon rumah dari Dokter {user1}.",
    "{user1} dipenggal {user2}.",
    "{user2} dilempari ... oleh massa yang marah.",
    "{user1} menggugat {user2}.",
    "{user2} adalah one-hit KO'd oleh {user1}.",
    "{user1} mengirim {user2} ke lubang memori.",
    "{user2} adalah kesalahan. - '{user1}'",
    "{user1} checkmated {user2} dalam dua gerakan.",
    "{user2} dibuat mubazir.",
    "{user1} {hits} {user2} dengan kelelawar !.",
    "{user1} {hits} {user2} dengan Taijutsu Kick !.",
    "{user1} {hits} {user2} with X-Gloves !.",
    "{user1} {hits} {user2} dengan Jet Punch !.",
    "{user1} {hits} {user2} dengan Jet Pistol !.",
    "{user1} {hits} {user2} dengan Amerika Serikat Smash !.",
    "{user1} {hits} {user2} dengan Detroit Smash !.",
    "{user1} {hits} {user2} dengan Texas Smash !.",
    "{user1} {hits} {user2} dengan California Smash !.",
    "{user1} {hits} {user2} dengan New Hampshire Smash !.",
    "{user1} {hits} {user2} dengan Missouri Smash !.",
    "{user1} {hits} {user2} dengan Carolina Smash !.",
    "{user1} {hits} {user2} dengan King Kong Gun !.",
    "{user1} {hits} {user2} dengan tongkat bisbol - logam.!.",
    "* Pukulan serius {user2} *.",
    "* Pukulan normal {user2} *.",
    "* Pukulan Normal berurutan {user2} *.",
    "* Pukulan Normal Berturut-turut Dua Tangan {user2} *.",
    "* Mengabaikan {user2} untuk membiarkan mereka mati karena malu *.",
    "* menunjuk ke {user2} * Ada apa dengan si lancang ... anak hilang ini ?.",
    "* Memukul {user2} dengan Fire Tornado *.",
    "{user1} menyodok {user2} di mata!",
    "{user1} menyodok {user2} di samping!",
    "{user1} menyodok {user2}!",
    "{user1} menyodok {user2} dengan jarum!",
    "{user1} menyodok {user2} dengan pena!",
    "{user1} menyodok {user2} dengan pistol bius!",
    "{user2} secara rahasia adalah Furry !.",
    "Hai Semuanya! {User1} meminta saya untuk menjadi jahat!",
    "(･ _ ･) ﾉ ⌒ ● ~ * (･. ･;) <- {user2}",
    "Ambil ini {pengguna2} \ n (ﾉ ﾟ Д ﾟ) ﾉ)))) ● ~ *",
    "Di sini {user2} pegang ini \ n (｀ ・ ω ・) つ ● ~ ＊",
    "(・ _ ・) ノ Ξ ● ~ * {user2}, Shinaeeeee !!.",
    "(・ ∀ ・) ｒ 鹵 ~ <≪ 巛; ﾟ Д ﾟ) ﾉ \ n * Semprotan bug {user2} *.",
    "(ﾟ Д ﾟ) ﾉ 占 ~ <巛 巛 巛. \ N- {user2} Kamu hama!",
    "(う -´) づ ︻╦̵̵ ╤── \ (˚☐˚”) / {user2}. ",
    "{user1} {hits} {user2} dengan {item}.",
    "{user1} {hits} {user2} di wajah dengan {item}.",
    "{user1} {hits} {user2} sekitar sedikit dengan {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} mengambil {item} dan {Throw} ke wajah {user2}.",
    "{user1} meluncurkan {item} ke arah umum {user2}.",
    "{user1} mulai menampar {user2} dengan konyol dengan {item}.",
    "{user1} pin {user2} ke bawah dan berulang kali {hits} mereka dengan {item}.",
    "{user1} mengambil {item} dan {hits} {user2} dengannya.",
    "{user1} mengikat {user2} ke kursi dan {melempar} {item} ke arah mereka.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lahar.",
    "{user1} menindas {user2}.",
    "Mau memakan kaki {user2}. * nyam nyam nyam *",
    "{user1} {throws} master ball ke {user2}, resistensi sia-sia.",
    "{user1} memukul {user2} dengan balok tindakan ... bbbbbb (ง ・ ω ・) ง ==== *",
    "{user1} ara ara {user2}.",
    "{user1} ora ora {user2}.",
    "{user1} muda {user2}.",
    "{user2} diubah menjadi referensi Jojo!",
    "{user1} klik {user2} dengan {item}.",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "wajan besi cor",
    "meong marah",
    "Anunya Tokai",
    "tongkat kayu",
    "sekop",
    "pemanggang roti",
    "Book",
    "laptop",
    "ayam karet",
    "Kolor viki",
    "batu berat",
    "kotoran zenn",
    "banyak batu bata",
    "rasengan",
    "Kepala Tata",
    "Celana dalam abdul",
    "rasenshuriken",
    "Murasame",
    "melarang",
    "chunchunmaru",
    "Pantat Toni",
    "rasengan",
    "Celana dalam apis",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",

)

ABUSE_STRINGS = (
    "Fuck off",
    "Stfu go fuck yourself",
    "Ur mum gey",
    "Ur dad lesbo",
    "Bsdk",
    "Nigga",
    "Ur granny tranny",
    "you noob",
    "Relax your Rear,ders nothing to fear,The Rape train is finally here",
    "Stfu bc",
    "Stfu and Gtfo U nub",
    "GTFO bsdk",
    "CUnt",
    " Gay is here",
    "Ur dad gey bc ",
)

EYES = [
    ['⌐■', '■'],
    [' ͠°', ' °'],
    ['⇀', '↼'],
    ['´• ', ' •`'],
    ['´', '`'],
    ['`', '´'],
    ['ó', 'ò'],
    ['ò', 'ó'],
    ['⸌', '⸍'],
    ['>', '<'],
    ['Ƹ̵̡', 'Ʒ'],
    ['ᗒ', 'ᗕ'],
    ['⟃', '⟄'],
    ['⪧', '⪦'],
    ['⪦', '⪧'],
    ['⪩', '⪨'],
    ['⪨', '⪩'],
    ['⪰', '⪯'],
    ['⫑', '⫒'],
    ['⨴', '⨵'],
    ['⩿', '⪀'],
    ['⩾', '⩽'],
    ['⩺', '⩹'],
    ['⩹', '⩺'],
    ['◥▶', '◀◤'],
    ['◍', '◎'],
    ['/͠-', '┐͡-\\'],
    ['⌣', '⌣”'],
    [' ͡⎚', ' ͡⎚'],
    ['≋'],
    ['૦ઁ'],
    ['  ͯ'],
    ['  ͌'],
    ['ළ'],
    ['◉'],
    ['☉'],
    ['・'],
    ['▰'],
    ['ᵔ'],
    [' ﾟ'],
    ['□'],
    ['☼'],
    ['*'],
    ['`'],
    ['⚆'],
    ['⊜'],
    ['>'],
    ['❍'],
    ['￣'],
    ['─'],
    ['✿'],
    ['•'],
    ['T'],
    ['^'],
    ['ⱺ'],
    ['@'],
    ['ȍ'],
    ['  '],
    ['  '],
    ['x'],
    ['-'],
    ['$'],
    ['Ȍ'],
    ['ʘ'],
    ['Ꝋ'],
    [''],
    ['⸟'],
    ['๏'],
    ['ⴲ'],
    ['◕'],
    ['◔'],
    ['✧'],
    ['■'],
    ['♥'],
    [' ͡°'],
    ['¬'],
    [' º '],
    ['⨶'],
    ['⨱'],
    ['⏓'],
    ['⏒'],
    ['⍜'],
    ['⍤'],
    ['ᚖ'],
    ['ᴗ'],
    ['ಠ'],
    ['σ'],
    ['☯']
]

MOUTHS = [
    ['v'],
    ['ᴥ'],
    ['ᗝ'],
    ['Ѡ'],
    ['ᗜ'],
    ['Ꮂ'],
    ['ᨓ'],
    ['ᨎ'],
    ['ヮ'],
    ['╭͜ʖ╮'],
    [' ͟ل͜'],
    [' ͜ʖ'],
    [' ͟ʖ'],
    [' ʖ̯'],
    ['ω'],
    [' ³'],
    [' ε '],
    ['﹏'],
    ['□'],
    ['ل͜'],
    ['‿'],
    ['╭╮'],
    ['‿‿'],
    ['▾'],
    ['‸'],
    ['Д'],
    ['∀'],
    ['!'],
    ['人'],
    ['.'],
    ['ロ'],
    ['_'],
    ['෴'],
    ['ѽ'],
    ['ഌ'],
    ['⏠'],
    ['⏏'],
    ['⍊'],
    ['⍘'],
    ['ツ'],
    ['益'],
    ['╭∩╮'],
    ['Ĺ̯'],
    ['◡'],
    [' ͜つ']
]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = (
    "Yes.",
    "NoU.",
    "Maybe."
)

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables."
)
